import type { DraftVersion, StableDraftExport } from './types';

/**
 * Produce a standalone ES module that only knows how to parse one draft.
 * The generated parser never throws on malformed input: every failure reports
 * { ok:false, errors:[{path,offset,message}] } and partial values.
 */
export function generateParserModule(draft: DraftVersion): string {
  const exportDoc: StableDraftExport = {
    schema: 'binary-format-inference-bench/draft',
    schemaVersion: 1,
    draft,
  };
  const serialized = JSON.stringify(exportDoc, null, 2);
  return `// Generated by 二进制格式推断台 — do not edit.
// Draft v${draft.version}: ${draft.label}
const DRAFT = ${serialized};

const INT_WIDTH = { u8:1, i8:1, u16:2, i16:2, u24:3, i24:3, u32:4, i32:4, u64:8, i64:8 };

function decodeInt(bytes, offset, kind, endian) {
  const width = INT_WIDTH[kind];
  let value = 0n;
  if (endian === 'little') {
    for (let i = width - 1; i >= 0; i--) value = (value << 8n) | BigInt(bytes[offset + i]);
  } else {
    for (let i = 0; i < width; i++) value = (value << 8n) | BigInt(bytes[offset + i]);
  }
  if (kind[0] === 'i') {
    const bits = BigInt(width * 8);
    const sign = 1n << (bits - 1n);
    if ((value & sign) !== 0n) value -= 1n << bits;
  }
  return value;
}

function decodeString(bytes, start, end, encoding, trimNul) {
  const slice = bytes.subarray(start, end);
  let text;
  if (encoding === 'utf16le') text = new TextDecoder('utf-16le').decode(slice);
  else if (encoding === 'utf16be') {
    const swapped = new Uint8Array(slice.length);
    for (let i = 0; i + 1 < slice.length; i += 2) {
      swapped[i] = slice[i + 1];
      swapped[i + 1] = slice[i];
    }
    text = new TextDecoder('utf-16le').decode(swapped);
  } else {
    text = new TextDecoder(encoding === 'ascii' ? 'latin1' : encoding).decode(slice);
  }
  return trimNul ? text.replace(/\\0+$/, '') : text;
}

function checksumValue(bytes, algorithm) {
  if (algorithm === 'xor8') {
    let v = 0;
    for (const b of bytes) v ^= b;
    return BigInt(v);
  }
  if (algorithm === 'sum8') {
    let v = 0;
    for (const b of bytes) v = (v + b) & 0xff;
    return BigInt(v);
  }
  if (algorithm.startsWith('sum16')) {
    let v = 0n;
    for (const b of bytes) v += BigInt(b);
    v &= 0xffffn;
    if (algorithm === 'sum16-le') v = ((v & 0xffn) << 8n) | ((v >> 8n) & 0xffn);
    return v;
  }
  // crc32
  const table = [];
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c >>> 0;
  }
  let crc = 0xffffffff;
  for (const b of bytes) crc = table[(crc ^ b) & 0xff] ^ (crc >>> 8);
  let v = BigInt((crc ^ 0xffffffff) >>> 0);
  if (algorithm === 'crc32-le') {
    v = ((v & 0xffn) << 24n) | (((v >> 8n) & 0xffn) << 16n) | (((v >> 16n) & 0xffn) << 8n) | ((v >> 24n) & 0xffn);
  }
  return v;
}

function parse(input) {
  const bytes = input instanceof Uint8Array ? input : new Uint8Array(input);
  const errors = [];
  const values = {};
  const fields = {};
  const fieldIdBySource = {};
  for (const field of DRAFT.draft.fields) fieldIdBySource[field.sourceHypothesisId] = field.id;
  const ref = (id) => (id === null || id === undefined ? null : (fields[id] ?? fields[fieldIdBySource[id]] ?? null));
  const pushError = (path, offset, message) => errors.push({ path, offset, message });
  const fail = (path, offset, message) => {
    pushError(path, offset, message);
    return null;
  };

  const ensureRange = (path, start, end) => {
    if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start < 0 || end < start) {
      pushError(path, start, \`非法区间 [\${start},\${end})\`);
      return false;
    }
    if (end > bytes.length) {
      pushError(path, Math.min(Math.max(start, 0), bytes.length), \`区间 [\${start},\${end}) 越界（样本长度 \${bytes.length}）\`);
      return false;
    }
    return true;
  };

  const resolveRegion = (path, region) => {
    if (region.kind === 'fixed') {
      const end = region.end === -1 ? bytes.length : region.end;
      if (!ensureRange(path, region.start, end)) return null;
      return [{ start: region.start, end }];
    }
    if (region.kind === 'prefixTo') {
      const anchor = ref(region.endField);
      if (!anchor) return fail(path, 0, '锚点字段缺失: ' + region.endField);
      if (!ensureRange(path, 0, anchor.range.start)) return null;
      return [{ start: 0, end: anchor.range.start }];
    }
    if (region.kind === 'between') {
      const a = ref(region.startField);
      const b = ref(region.endField);
      if (!a || !b) return fail(path, 0, '区间边界字段缺失');
      if (!ensureRange(path, a.range.end, b.range.start)) return null;
      return [{ start: a.range.end, end: b.range.start }];
    }
    const lengthField = ref(region.lengthField);
    if (!lengthField) return fail(path, region.startConst, '长度字段缺失: ' + region.lengthField);
    const start = region.startField ? (ref(region.startField)?.range.end ?? null) : region.startConst;
    if (start === null) return fail(path, 0, '起始字段缺失: ' + region.startField);
    const size = lengthField.value * BigInt(1);
    if (size < 0n || size > (1n << 40n)) return fail(path, start, '长度溢出');
    const end = Number(BigInt(start) + size);
    if (!ensureRange(path, start, end)) return null;
    return [{ start, end }];
  };

  const ordered = [...DRAFT.draft.fields].sort((a, b) => a.range.start - b.range.start);
  for (const field of ordered) {
    const path = '$.' + field.name;
    const cfg = field.config;
    if (!ensureRange(path, field.range.start, field.range.end)) {
      fields[field.id] = { range: field.range, value: null };
      continue;
    }
    if (cfg.type === 'integer') {
      const width = INT_WIDTH[cfg.intKind];
      if (field.range.end - field.range.start < width) {
        pushError(path, field.range.start, '区间窄于声明整数宽度');
        continue;
      }
      const value = decodeInt(bytes, field.range.start, cfg.intKind, cfg.endian);
      fields[field.id] = { range: field.range, value };
      values[field.name] = value.toString();
      continue;
    }
    if (cfg.type === 'string') {
      const value = decodeString(bytes, field.range.start, field.range.end, cfg.encoding, cfg.trimNul);
      fields[field.id] = { range: field.range, value: 0n };
      values[field.name] = value;
      continue;
    }
    if (cfg.type === 'enum') {
      const width = INT_WIDTH[cfg.intKind];
      const value = decodeInt(bytes, field.range.start, cfg.intKind, cfg.endian);
      const label = cfg.mapping[value.toString()];
      if (label === undefined) pushError(path, field.range.start, '枚举值不在映射表: ' + value.toString());
      fields[field.id] = { range: field.range, value };
      values[field.name] = { value: value.toString(), label: label ?? null };
      continue;
    }
    if (cfg.type === 'offset' || cfg.type === 'length' || cfg.type === 'offsetTable' || cfg.type === 'checksum') {
      const width = cfg.type === 'offsetTable' ? INT_WIDTH[cfg.entryKind]
        : cfg.type === 'checksum' ? (cfg.algorithm.includes('16') ? 2 : cfg.algorithm.includes('crc') ? 4 : 1)
        : INT_WIDTH[cfg.intKind];
      if (field.range.end - field.range.start < width) {
        pushError(path, field.range.start, '区间窄于声明整数宽度');
        continue;
      }
      const endian = cfg.type === 'offsetTable' ? cfg.endian
        : cfg.type === 'checksum' ? (cfg.algorithm.endsWith('-le') ? 'little' : 'big')
        : cfg.endian;
      const intKind = cfg.type === 'offsetTable' ? cfg.entryKind
        : cfg.type === 'checksum' ? (width === 1 ? 'u8' : width === 2 ? 'u16' : 'u32')
        : cfg.intKind;
      const value = decodeInt(bytes, field.range.start, intKind, endian);
      fields[field.id] = { range: field.range, value };
      values[field.name] = value.toString();

      if (cfg.type === 'offset') {
        try {
          const scaled = value * BigInt(cfg.unit);
          if (scaled < 0n || scaled > (1n << 40n)) throw new Error('偏移溢出');
          let baseOffset = 0n;
          if (cfg.base === 'document-end') baseOffset = BigInt(bytes.length);
          if (cfg.base === 'field-start' || cfg.base === 'field-end') {
            const anchor = ref(cfg.anchorField);
            if (!anchor || anchor.value === null) { pushError(path, field.range.start, '锚点字段缺失'); continue; }
            baseOffset = BigInt(cfg.base === 'field-start' ? anchor.range.start : anchor.range.end);
          }
          const target = Number(baseOffset + scaled);
          if (target < 0 || target > bytes.length) {
            pushError(path, field.range.start, \`偏移目标 \${target} 越界（样本长度 \${bytes.length}）\`);
          } else {
            values[field.name + '.$target'] = target;
          }
        } catch (error) {
          pushError(path, field.range.start, error.message);
        }
        continue;
      }
      if (cfg.type === 'length') {
        const ranges = resolveRegion(path + '.$region', cfg.region);
        if (ranges) {
          const actual = ranges.reduce((acc, range) => acc + (range.end - range.start), 0);
          const declared = Number(value * BigInt(cfg.unit));
          if (declared !== actual) {
            pushError(path, ranges[0].start, \`声明长度 \${declared} 与实际区域长度 \${actual} 不符\`);
          }
          values[field.name + '.$region'] = ranges;
        }
        continue;
      }
      if (cfg.type === 'offsetTable') {
        let count = 0;
        if (typeof cfg.count === 'number') count = cfg.count;
        else {
          const countField = ref(cfg.count.field);
          if (!countField || countField.value === null) {
            pushError(path, field.range.start, '表项计数字段缺失');
            continue;
          }
          count = Number(countField.value);
        }
        const entryWidth = INT_WIDTH[cfg.entryKind];
        if (count * entryWidth > field.range.end - field.range.start) {
          pushError(path, field.range.start, \`偏移表需要 \${count * entryWidth} 字节，区间不足\`);
          continue;
        }
        let baseOffset = 0n;
        if (cfg.base === 'document-end') baseOffset = BigInt(bytes.length);
        if (cfg.base === 'field-start' || cfg.base === 'field-end') {
          const anchor = ref(cfg.anchorField);
          if (anchor) baseOffset = BigInt(cfg.base === 'field-start' ? anchor.range.start : anchor.range.end);
        }
        const targets = [];
        for (let i = 0; i < count; i++) {
          const at = field.range.start + i * entryWidth;
          const entry = decodeInt(bytes, at, cfg.entryKind, cfg.endian);
          const scaled = entry * BigInt(cfg.unit);
          const target = Number(baseOffset + scaled);
          targets.push(target);
          if (scaled < 0n || scaled > (1n << 40n) || target < 0 || target >= bytes.length) {
            pushError(path + '[' + i + ']', at, \`表项 \${entry.toString()} 解析到 \${target}，越界\`);
          }
        }
        values[field.name + '.$entries'] = targets;
        continue;
      }
      if (cfg.type === 'checksum') {
        try {
          const pieces = [];
          for (const region of cfg.covered) {
            const ranges = resolveRegion(path + '.$covered', region);
            if (!ranges) { pieces.length = 0; break; }
            pieces.push(...ranges);
          }
          if (pieces.length > 0) {
            const total = pieces.reduce((acc, range) => acc + (range.end - range.start), 0);
            const covered = new Uint8Array(total);
            let cursor = 0;
            for (const range of pieces) {
              covered.set(bytes.subarray(range.start, range.end), cursor);
              cursor += range.end - range.start;
            }
            const expected = checksumValue(covered, cfg.algorithm);
            values[field.name + '.$expected'] = expected.toString();
            if (expected !== value) {
              pushError(path, field.range.start, \`校验值 \${value.toString()} 与计算值 \${expected.toString()} 不符\`);
            }
          }
        } catch (error) {
          pushError(path, field.range.start, error.message);
        }
      }
    }
  }

  return {
    ok: errors.length === 0,
    draftVersion: DRAFT.draft.version,
    values,
    errors,
  };
}

export { DRAFT, parse };
export default { parse };
`;
}
