import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { transpileModule, ModuleKind, ScriptTarget } from 'typescript';
import type { Draft } from './types.js';
import { buildStableExport } from './draft.js';

let engineSourceCache: string | null = null;

export function engineSource(): string {
  if (engineSourceCache !== null) return engineSourceCache;
  const here = dirname(fileURLToPath(import.meta.url));
  const candidates = [
    join(here, 'parserEngine.js'),
    join(here, 'parserEngine.ts'),
    join(process.cwd(), 'src/core/parserEngine.ts'),
  ];
  for (const candidate of candidates) {
    try {
      engineSourceCache = readFileSync(candidate, 'utf8');
      return engineSourceCache;
    } catch {
      // try next candidate
    }
  }
  throw new Error('parserEngine source not found');
}

/**
 * Generates a self-contained ECMAScript module. It only parses — it never
 * mutates, never accesses the network, and returns {ok:false, path, offset}
 * on malformed/out-of-bounds input instead of throwing.
 */
export function generateParser(draft: Draft, versionNumber?: number): string {
  const exportObj = buildStableExport(draft, versionNumber);
  const transpiled = transpileModule(engineSource(), {
    compilerOptions: {
      module: ModuleKind.ESNext,
      target: ScriptTarget.ES2022,
      removeComments: false,
      sourceMap: false,
    },
  }).outputText.replace(/^\/\/\/\s*<reference[^>]*>\n?/gm, '');

  return `// Generated by 二进制格式推断台 — do not edit by hand.
// Source draft: ${exportObj.name} v${exportObj.version} (${exportObj.canonicalHash})
//
// Usage:
//   import { parse } from './parser-generated.mjs';
//   const result = parse(uint8ArrayOrNumberArray);
//   if (!result.ok) {
//     // result.path  -> JSON pointer such as "$.table[2]"
//     // result.offset-> absolute byte offset in the input
//     // result.code  -> out_of_bounds | overflow | invalid_enum | invalid_string
//   }
const DRAFT = ${JSON.stringify(exportObj, null, 2)};

${transpiled.trimEnd()}

export const draftMeta = {
  name: DRAFT.name,
  version: DRAFT.version,
  canonicalHash: DRAFT.canonicalHash,
  format: DRAFT.format,
};

export function parse(input) {
  return parseWithDraft(input, DRAFT);
}

export default { parse, draftMeta, parseWithDraft };
`;
}
